import { randomUUID } from 'node:crypto';
import path from 'node:path';
import { validateSpecification } from '../documents/documentCore.js';
import { validateSpecification as validatePresentationSpecification } from '../presentations/presentationCore.js';

const modes = new Set(['RESEARCH', 'DEVELOPMENT', 'DOCUMENT', 'PRESENTATION']);
const terminal = new Set(['COMPLETED', 'FAILED', 'BLOCKED', 'CANCELLED']);
const fail = (code, message, status = 400) => Object.assign(new Error(message), { code, status });
const requestText = value => { if (typeof value !== 'string' || !value.trim() || value.length > 4000 || value.includes('\0')) throw fail('MISSION_INVALID', 'Mission request is invalid.'); return value.trim(); };
const titleText = (value, request) => { const text = typeof value === 'string' && value.trim() ? value.trim() : request.slice(0, 80); if (text.length > 120 || /[\0\r\n]/.test(text)) throw fail('MISSION_INVALID', 'Mission title is invalid.'); return text; };
const status = value => value === 'WAITING_FOR_APPROVAL' ? 'WAITING_APPROVAL' : value;
const bounded = value => typeof value === 'string' ? value.slice(0, 4000) : value;
const safeArtifact = item => {
  let value = item.value;
  if (item.type === 'PATCH_PROPOSAL') value = { summary: value?.summary, fingerprint: value?.fingerprint, files: (value?.files || []).map(file => ({ path: file.path, operation: file.operation, content: bounded(file.content), baseHash: file.baseHash, purpose: file.purpose })) };
  else if (item.type === 'DEVELOPMENT_CONTEXT') value = { files: (value?.files || []).map(file => ({ relativePath: file.relativePath, contentHash: file.contentHash, selectionReasons: file.selectionReasons, ranges: file.ranges?.map(range => ({ startLine: range.startLine, endLine: range.endLine })) })), symbols: value?.symbols?.length || 0, knowledgeChunks: value?.knowledgeChunks?.length || 0, estimatedTokens: value?.estimatedTokens, pressure: value?.pressure };
  else if (item.type === 'TEST_RESULT') value = { commandId: value?.commandId, status: value?.status, code: value?.code, durationMs: value?.durationMs, stdout: bounded(value?.stdout), stderr: bounded(value?.stderr) };
  else if (value && typeof value === 'object') { value = structuredClone(value); delete value.reasoningSummary; delete value.prompt; }
  return { artifactId: item.artifactId, type: item.type, taskId: item.taskId, creatorAgent: item.creatorAgent, createdAt: item.createdAt, validationStatus: item.validationStatus, value };
};

export class MissionService {
  constructor({ store, projects, core, models }) { this.store = store; this.projects = projects; this.core = core; this.models = models; this.locks = new Map(); this.activeRuns = new Map(); }
  async save() { await this.store.save(); }
  create(projectId, input = {}) {
    const project = this.projects.get(projectId), request = requestText(input.request), mode = String(input.mode || '').toUpperCase();
    if (!modes.has(mode)) throw fail('MISSION_INVALID', 'Mission mode is invalid.');
    const documentRequirements = mode === 'DOCUMENT' ? validateSpecification(input.document || {}, request) : null;
    const presentationRequirements = mode === 'PRESENTATION' ? validatePresentationSpecification(input.presentation || {}, request) : null;
    const presentationInput = presentationRequirements ? Object.fromEntries(Object.keys(input.presentation || {}).filter(key => ['title', 'purpose', 'audience', 'language', 'tone', 'presentationType', 'targetSlideCount', 'durationMinutes', 'period', 'theme', 'sourcePolicy', 'requiredTopics', 'allowPlaceholders'].includes(key)).map(key => [key, input.presentation[key]])) : null;
    // Explicit/free-text slide count is a user constraint; other unspecified
    // fields remain available for the PresentationPlannerAgent to infer.
    if (presentationInput && /\b\d{1,3}[ -]slides?\b/i.test(request) && presentationInput.targetSlideCount === undefined) presentationInput.targetSlideCount = presentationRequirements.targetSlideCount;
    const now = new Date().toISOString(), mission = { id: randomUUID(), projectId: project.id, title: titleText(input.title || documentRequirements?.title || presentationRequirements?.title, request), request, mode, status: 'READY', dryRun: mode === 'DEVELOPMENT' ? input.dryRun !== false : true, documentRequirements, presentationRequirements, presentationInput, createdAt: now, updatedAt: now, currentRunId: null, cancellationRequested: false };
    this.store.state.missions.push(mission); this.projects.activity(projectId, 'MISSION_CREATED', { missionId: mission.id, mode }); return this.save().then(() => this.publicMission(mission));
  }
  get(id) { const mission = this.store.state.missions.find(item => item.id === id); if (!mission) throw fail('MISSION_NOT_FOUND', 'Mission was not found.', 404); return mission; }
  getForProject(projectId, id) { if (!projectId) throw fail('PROJECT_REQUIRED', 'Project scope is required.'); const mission = this.get(id); if (mission.projectId !== projectId) throw fail('MISSION_NOT_FOUND', 'Mission was not found.', 404); return mission; }
  list(projectId, query = '') { this.projects.get(projectId); const value = String(query).toLowerCase().slice(0, 100); return this.store.state.missions.filter(item => item.projectId === projectId && (!value || item.title.toLowerCase().includes(value) || item.request.toLowerCase().includes(value))).map(item => this.publicMission(item)); }
  publicMission(item) { const runs = this.store.state.runs.filter(run => run.missionId === item.id); return { id: item.id, projectId: item.projectId, title: item.title, request: item.request, mode: item.mode, status: item.status, dryRun: item.dryRun, documentRequirements: item.documentRequirements || null, presentationRequirements: item.presentationRequirements || null, createdAt: item.createdAt, updatedAt: item.updatedAt, currentRunId: item.currentRunId, runCount: runs.length, latestRun: runs.at(-1) ? this.publicRun(runs.at(-1)) : null }; }
  publicRun(run) {
    if (run.mode === 'PRESENTATION' && run.status === 'RUNNING' && run.jobId) {
      const job = this.core.getJob(run.jobId), s = job.presentationState;
      run.tasks = job.tasks.map(t => ({ taskId: t.taskId, type: t.type, title: t.title, role: t.assignedAgent, status: status(t.status), attempt: t.attempt, summary: t.result?.summary, startedAt: t.startedAt, completedAt: t.completedAt }));
      if (s) run.presentation = { specification: s.specification, storyboard: s.storyboard, narrativePlan: s.narrativePlan, revision: s.revision, fingerprint: s.fingerprint, grounding: s.grounding, qa: s.qa, review: { status: s.status, issues: s.issues }, metrics: s.metrics };
    }
    return { id: run.id, missionId: run.missionId, projectId: run.projectId, jobId: run.jobId, mode: run.mode, status: run.status, dryRun: run.dryRun, startedAt: run.startedAt, completedAt: run.completedAt, tasks: run.tasks, models: run.models, context: run.context, document: run.document || null, presentation: run.presentation || null, artifactRefs: run.artifactRefs, approvalState: run.approvalState, testResult: run.testResult, finalResult: run.finalResult, errorCode: run.errorCode, cancellationRequested: run.cancellationRequested };
  }
  runs(missionId, projectId) { const mission = this.getForProject(projectId, missionId); return this.store.state.runs.filter(item => item.missionId === mission.id).map(item => this.publicRun(item)); }
  getRun(id) { const run = this.store.state.runs.find(item => item.id === id); if (!run) throw fail('RUN_NOT_FOUND', 'Mission run was not found.', 404); return run; }
  acquire(workspaceId, runId) { const current = this.locks.get(workspaceId); if (current && current !== runId) throw fail('WORKSPACE_BUSY', 'Another write-capable mission is using this workspace.', 409); this.locks.set(workspaceId, runId); }
  release(workspaceId, runId) { if (this.locks.get(workspaceId) === runId) this.locks.delete(workspaceId); }
  validateOverrides(value = {}) { return this.projects.validatePreferences(value); }
  async run(missionId, options = {}) {
    const mission = this.getForProject(options.projectId, missionId), project = this.projects.get(mission.projectId); if (['RUNNING', 'WAITING_APPROVAL'].includes(mission.status)) throw fail('MISSION_BUSY', 'Mission already has an active run.', 409); if (project.workspaceStatus !== 'ACTIVE' && mission.mode === 'DEVELOPMENT') throw fail('WORKSPACE_UNAVAILABLE', 'Project workspace is unavailable.', 409);
    const dryRun = mission.mode === 'DEVELOPMENT' ? options.dryRun ?? mission.dryRun : true, runOverrides = this.validateOverrides(options.modelOverrides || {}), modelOverrides = { ...project.modelPreferences, ...runOverrides }, providerMode = options.providerMode || 'local'; if (!['local', 'openai', 'auto'].includes(providerMode)) throw fail('PROVIDER_MODE_INVALID', 'Invalid provider mode.');
    const run = { id: randomUUID(), missionId: mission.id, projectId: project.id, jobId: null, mode: mission.mode, status: 'RUNNING', dryRun, startedAt: new Date().toISOString(), completedAt: null, tasks: [], models: [], context: null, artifactRefs: [], approvalState: null, testResult: null, finalResult: null, errorCode: null, cancellationRequested: false };
    if (mission.mode === 'DEVELOPMENT' && !dryRun) { if (!project.testCommands.length) throw fail('TESTS_REQUIRED', 'Write-capable missions require registered tests.'); this.acquire(project.workspaceId, run.id); }
    this.store.state.runs.push(run); mission.currentRunId = run.id; mission.status = 'RUNNING'; mission.updatedAt = run.startedAt; this.projects.activity(project.id, 'MISSION_STARTED', { missionId, runId: run.id }); await this.save();
    try {
      let job;
      if (mission.mode === 'RESEARCH') job = this.core.createJob(mission.request, { projectId: project.knowledgeProjectId, kind: 'research', maxIterations: 3, metadata: { research: { topK: 5, maxContextTokens: 2000, maxAttempts: 3, providerMode, modelOverrides } } });
      else if (mission.mode === 'DOCUMENT') job = this.core.createJob(mission.request, { projectId: project.id, kind: 'document', maxIterations: 20, metadata: { document: { missionId: mission.id, runId: run.id, userRequest: mission.request, requirements: mission.documentRequirements, sourceIds: project.sourceIds, repositoryIds: project.repositoryIds, providerMode, modelOverrides } } });
      else if (mission.mode === 'PRESENTATION') job = this.core.createJob(mission.request, { projectId: project.id, kind: 'presentation', maxIterations: 40, metadata: { presentation: { missionId: mission.id, runId: run.id, userRequest: mission.request, requirements: mission.presentationRequirements, userRequirements: mission.presentationInput, sourceIds: [...project.sourceIds], repositoryIds: [...project.repositoryIds], providerMode, modelOverrides } } });
      else {
        const development = { projectId: project.id, workspaceId: project.workspaceId, request: mission.request, acceptanceCriteria: [mission.request], allowedPaths: project.allowedPaths, deniedPaths: project.deniedPaths, testCommandIds: project.testCommands.map(item => item.id), contextFiles: project.allowedPaths.filter(item => item !== '.'), maxFilesChanged: 10, maxPatchBytes: 100000, maxIterations: 2, allowCreateFiles: false, allowDeleteFiles: false, allowGitRead: true, allowGitWrite: false, dryRun, orchestrationVersion: 2, providerMode, modelOverrides, repositoryId: project.repositoryIds[0] || null };
        job = this.core.createJob(mission.request, { projectId: project.id, kind: 'development', maxIterations: 30, metadata: { development, mission: { missionId, runId: run.id } } });
      }
      run.jobId = job.jobId; this.activeRuns.set(run.id, job.jobId); const result = await this.core.run(job.jobId); await this.capture(run, mission, result); return this.detailRun(run.id, project.id);
    } catch (error) { if (mission.mode === 'PRESENTATION' && run.jobId) await this.capture(run, mission, this.core.details(run.jobId)); run.status = 'FAILED'; run.errorCode = error.code || 'MISSION_RUN_FAILED'; run.completedAt = new Date().toISOString(); mission.status = 'FAILED'; mission.updatedAt = run.completedAt; this.projects.activity(project.id, 'MISSION_FAILED', { missionId, runId: run.id, code: run.errorCode }); await this.save(); throw error; }
    finally { this.activeRuns.delete(run.id); if (mission.mode === 'DEVELOPMENT' && !dryRun && terminal.has(run.status)) this.release(project.workspaceId, run.id); }
  }
  async capture(run, mission, details) {
    if (details.presentationState) {
      const s = details.presentationState;
      run.presentation = { specification: s.specification, narrativePlan: s.narrativePlan, storyboard: s.storyboard, fingerprint: s.fingerprint, revision: s.revision, revisions: s.revisions, metrics: { ...s.metrics, calls: this.models?.calls?.filter(c => c.jobId === details.jobId).length || 0 }, performance: s.performance, grounding: s.grounding, review: { status: s.status, issues: s.issues }, qa: s.qa, pptxQa: s.pptxQa, noProgress: s.noProgress, retrieval: s.evidencePack?.retrieval };
      for (const item of (details.artifacts || []).filter(a => a.type === 'PRESENTATION_FILE' && a.path)) if (!this.store.state.presentationArtifacts.some(a => a.artifactId === item.artifactId)) this.store.state.presentationArtifacts.push({ ...item.value, artifactId: item.artifactId, projectId: run.projectId, missionId: run.missionId, runId: run.id, path: item.path });
    }
    const calls = this.models?.calls?.filter(item => item.jobId === details.jobId) || [], context = details.artifacts?.filter(item => item.type === 'DEVELOPMENT_CONTEXT').at(-1)?.value;
    run.status = status(details.status); run.tasks = details.tasks.map(task => ({ taskId: task.taskId, type: task.type || task.key, title: task.title, role: task.assignedAgent, status: status(task.status), attempt: task.attempt, startedAt: task.startedAt, completedAt: task.completedAt, summary: task.result?.summary || null }));
    run.models = calls.map(call => ({ taskId: call.taskId, role: call.role, provider: call.provider, model: call.model, status: call.status, durationMs: call.durationMs, inputTokens: call.usage?.inputTokens ?? null, outputTokens: call.usage?.outputTokens ?? null, retry: call.retry, errorCode: call.errorCode }));
    run.context = context ? { files: context.files?.length || 0, ranges: context.files?.reduce((sum, file) => sum + (file.ranges?.length || 0), 0) || 0, symbols: context.symbols?.length || 0, qdrantChunks: context.knowledgeChunks?.length || 0, estimatedTokens: context.estimatedTokens ?? context.budget?.estimatedTokens ?? null, pressure: context.pressure ?? context.budget?.pressure ?? 'UNKNOWN', paths: (context.files || []).map(file => ({ path: file.relativePath, reasons: file.selectionReasons || [] })) } : null;
    run.artifactRefs = (details.artifacts || []).map(item => ({ artifactId: item.artifactId, type: item.type, taskId: item.taskId, createdAt: item.createdAt })); for (const item of (details.artifacts || []).filter(item => item.type === 'DOCUMENT_FILE' && item.path)) if (!this.store.state.documentArtifacts.some(saved => saved.artifactId === item.artifactId)) this.store.state.documentArtifacts.push({ artifactId: item.artifactId, projectId: run.projectId, missionId: run.missionId, runId: run.id, ...item.value, path: item.path }); run.approvalState = details.approvals?.at(-1)?.status || null; run.testResult = details.artifacts?.filter(item => item.type === 'TEST_RESULT').at(-1)?.value?.status || null; run.document = details.documentState ? { specification: details.documentState.specification, fingerprint: details.documentState.fingerprint, revision: details.documentState.revision, revisions: details.documentState.revisions, metrics: details.documentState.metrics, grounding: details.documentState.grounding, review: details.documentState.review, qa: details.documentState.qa } : null; run.finalResult = details.finalReview ? { status: details.finalReview.status, summary: details.finalReview.summary, passed: details.finalReview.data?.passed } : details.groundedResult || null; run.errorCode = details.failureReason || null;
    if (terminal.has(run.status)) run.completedAt = new Date().toISOString(); mission.status = run.status; mission.updatedAt = new Date().toISOString(); this.projects.activity(run.projectId, run.status === 'COMPLETED' ? 'MISSION_COMPLETED' : run.status === 'WAITING_APPROVAL' ? 'APPROVAL_REQUIRED' : 'MISSION_FAILED', { missionId: mission.id, runId: run.id, status: run.status }); await this.save();
  }
  detailRun(id, projectId = null) { const run = this.getRun(id); if (projectId && run.projectId !== projectId) throw fail('RUN_NOT_FOUND', 'Mission run was not found.', 404); return this.publicRun(run); }
  document(id, projectId) { const run = this.getRun(id); if (!projectId || run.projectId !== projectId || run.mode !== 'DOCUMENT') throw fail('RUN_NOT_FOUND', 'Mission run was not found.', 404); return { document: run.document, artifacts: this.store.state.documentArtifacts.filter(item => item.runId === id).map(({ path: _path, ...item }) => item) }; }
  presentation(id, projectId) { const run = this.getRun(id); if (!projectId || run.projectId !== projectId || run.mode !== 'PRESENTATION') throw fail('RUN_NOT_FOUND', 'Mission run was not found.', 404); return { presentation: run.presentation, artifacts: this.store.state.presentationArtifacts.filter(item => item.runId === id && item.projectId === projectId).map(({ path: _path, ...item }) => item) }; }
  preview(id, projectId) { const run = this.getRun(id); if (!projectId || run.projectId !== projectId || !run.jobId) throw fail('RUN_NOT_FOUND', 'Mission run was not found.', 404); const draft = this.core.details(run.jobId).artifacts.filter(item => item.type === (run.mode === 'PRESENTATION' ? 'PRESENTATION_DRAFT' : 'DOCUMENT_DRAFT')).at(-1); return { ir: draft?.value || null }; }
  evidence(id, projectId) { const run = this.getRun(id); if (!projectId || run.projectId !== projectId || !run.jobId) throw fail('RUN_NOT_FOUND', 'Mission run was not found.', 404); const pack = this.core.details(run.jobId).artifacts.find(item => item.type === 'EVIDENCE_PACK')?.value; return { evidence: (pack?.items || []).map(item => ({ id: item.id, sourceType: item.sourceType, provenance: item.provenance, excerpt: item.text.slice(0, 500), supports: item.supports })), coverage: pack?.coverage || [] }; }
  download(artifactId, projectId) { if (!projectId) throw fail('PROJECT_REQUIRED', 'Project scope is required.'); const item = [...this.store.state.documentArtifacts, ...this.store.state.presentationArtifacts].find(value => value.artifactId === artifactId && value.projectId === projectId); if (!item) throw fail('ARTIFACT_NOT_FOUND', 'Artifact was not found.', 404); if (this.store.state.presentationArtifacts.includes(item)) { const expected = path.resolve(path.dirname(this.store.file), 'artifacts', item.projectId, item.missionId, item.runId, item.filename); if (!/^[0-9a-f-]{36}$/i.test(item.projectId) || !/^[0-9a-f-]{36}$/i.test(item.missionId) || !/^[0-9a-f-]{36}$/i.test(item.runId) || path.basename(item.filename) !== item.filename || path.resolve(item.path) !== expected) throw fail('ARTIFACT_NOT_FOUND', 'Artifact was not found.', 404); } return item; }
  artifacts(runId, projectId = null) { const run = this.getRun(runId); if (projectId && run.projectId !== projectId) throw fail('RUN_NOT_FOUND', 'Mission run was not found.', 404); if (!run.jobId) return []; try { return this.core.details(run.jobId).artifacts.map(safeArtifact); } catch { return run.artifactRefs; } }
  approvals(runId, projectId = null) { const run = this.getRun(runId); if (projectId && run.projectId !== projectId) throw fail('RUN_NOT_FOUND', 'Mission run was not found.', 404); if (!run.jobId) return []; return this.core.store.listApprovals(run.jobId).map(item => ({ approvalId: item.approvalId, projectId: item.projectId, jobId: item.jobId, taskId: item.taskId, status: item.status, requestedAt: item.requestedAt, resolvedAt: item.resolvedAt, requestPreview: item.requestPreview, riskLevel: item.riskLevel })); }
  async resolveApproval(runId, approvalId, decision, projectId) { const run = this.getRun(runId); if (!projectId || run.projectId !== projectId) throw fail('RUN_NOT_FOUND', 'Mission run was not found.', 404); const mission = this.get(run.missionId), project = this.projects.get(run.projectId), approval = this.core.approvals.get(approvalId); if (approval.jobId !== run.jobId || approval.projectId !== project.id) throw fail('APPROVAL_MISMATCH', 'Approval does not belong to this mission run.', 409); const details = decision === 'APPROVED' ? await this.core.approve(approvalId) : this.core.deny(approvalId); this.projects.activity(project.id, decision === 'APPROVED' ? 'PATCH_APPROVED' : 'PATCH_REJECTED', { missionId: mission.id, runId, approvalId }); await this.capture(run, mission, details); if (terminal.has(run.status)) this.release(project.workspaceId, run.id); return this.detailRun(run.id); }
  async cancel(missionId, projectId) { const mission = this.getForProject(projectId, missionId); if (terminal.has(mission.status)) throw fail('MISSION_NOT_ACTIVE', 'Mission is not active.', 409); const run = mission.currentRunId && this.getRun(mission.currentRunId); if (!run) { mission.status = 'CANCELLED'; mission.updatedAt = new Date().toISOString(); await this.save(); return this.publicMission(mission); } run.cancellationRequested = true; mission.cancellationRequested = true; if (mission.status === 'WAITING_APPROVAL') { const pending = this.core.store.listApprovals(run.jobId).find(item => item.status === 'PENDING'); if (pending) this.core.deny(pending.approvalId); run.status = mission.status = 'CANCELLED'; run.completedAt = mission.updatedAt = new Date().toISOString(); this.release(this.projects.get(mission.projectId).workspaceId, run.id); } this.projects.activity(mission.projectId, 'MISSION_CANCELLATION_REQUESTED', { missionId, runId: run.id }); await this.save(); return this.publicMission(mission); }
}
