import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import { ModelRegistry } from '../src/models/modelRegistry.js';
import { ModelGateway } from '../src/models/modelGateway.js';
import { AiSettingsService } from '../src/models/aiSettingsService.js';
import { ModelSelectionService } from '../src/models/modelSelectionService.js';
import { ModelLab } from '../src/models/modelLab.js';
import { AiControlCenter, aiRouter } from '../src/models/aiControlCenter.js';

const responseFor = prompt => { const value = JSON.parse(prompt); if (value.expected?.goal) return { goal: 'Add greeting', tasks: ['inspect', 'edit', 'test'], risks: [] }; if (value.expected?.summary) return { summary: 'Update greeting', files: [{ path: 'src/greet.js', content: 'export const greet=()=>"Hello";' }] }; if (value.knownIssue) return { status: 'FAIL', issues: ['No zero guard'] }; if (value.testFailure) return { diagnosis: 'Wrong return value', repairInstructions: ['Return Hello'] }; return { ok: true, label: 'control' }; };
const setup = ({ healthy = true } = {}) => {
  const registry = new ModelRegistry();
  for (const id of ['chat-a', 'chat-b']) registry.register({ modelId: id, providerId: 'ollama', displayName: id, capabilities: ['chat'], purposes: ['GENERAL'], enabled: true });
  registry.register({ modelId: 'embed-a', providerId: 'ollama', displayName: 'embed-a', capabilities: ['embedding'], purposes: ['EMBEDDING'], enabled: true });
  const calls = [], provider = { id: 'ollama', capabilities: ['chat', 'embedding'], health: async () => healthy, listModels: async () => ['chat-a', 'chat-b', 'embed-a'], generate: async input => { calls.push(input); return { content: JSON.stringify(responseFor(input.prompt)), usage: { inputTokens: 10, outputTokens: 5 } }; }, embed: async () => [[1, 0]] };
  const gateway = new ModelGateway({ registry, timeoutMs: 100 }); gateway.registerProvider(provider);
  const settings = new AiSettingsService({ registry, defaults: { runtimeProvider: 'local', roles: Object.fromEntries(['general', 'planner', 'research', 'development', 'review', 'critic'].map(role => [role, 'chat-a'])), embedding: { provider: 'ollama', model: 'embed-a' } } });
  const selection = new ModelSelectionService({ registry, settings, providers: gateway.providers }); gateway.setSelectionService(selection);
  const lab = new ModelLab({ gateway, registry, maxHistory: 3 });
  return { registry, calls, gateway, settings, selection, lab };
};

test('settings validate providers, roles, chat and embedding capability', () => { const { settings } = setup(); assert.throws(() => settings.update({ runtimeProvider: '../../powershell' }), /Invalid runtime/); assert.throws(() => settings.update({ roles: { development: 'embed-a' } }), /does not support chat/); assert.throws(() => settings.update({ embedding: { provider: 'ollama', model: 'chat-a' } }), /does not support embedding/); assert.throws(() => settings.update({ roles: { root: 'chat-a' } }), /Invalid runtime role/); });
test('settings changes are process local, audited, and contain no secret fields', () => { const { settings } = setup(); const changed = settings.update({ runtimeProvider: 'auto', roles: { critic: 'chat-b' } }); assert.equal(changed.roles.critic, 'chat-b'); assert.deepEqual(settings.events.map(item => item.type), ['AI_PROVIDER_CHANGED', 'ROLE_MODEL_CHANGED']); assert.equal(JSON.stringify(settings.public()).includes('apiKey'), false); });
test('local and auto select healthy local while openai is structured unconfigured', async () => { const { selection } = setup(); assert.equal((await selection.resolve({ role: 'planner' })).actualModel, 'chat-a'); assert.equal((await selection.resolve({ role: 'planner', providerMode: 'auto' })).actualProvider, 'ollama'); await assert.rejects(selection.resolve({ providerMode: 'openai' }), error => error.code === 'PROVIDER_NOT_CONFIGURED'); });
test('missing role assignment follows observable general fallback', async () => { const { settings, selection } = setup(); settings.value.roles.development = 'removed'; const result = await selection.resolve({ role: 'development' }); assert.equal(result.actualModel, 'chat-a'); assert.equal(result.fallback, true); assert.equal(result.reason, 'ROLE_MODEL_MISSING_GENERAL_FALLBACK'); assert.equal(selection.events.at(-1).type, 'MODEL_FALLBACK'); });
test('unavailable auto mode returns a structured failure', async () => { const { selection } = setup({ healthy: false }); await assert.rejects(selection.resolve({ providerMode: 'auto' }), error => error.code === 'PROVIDER_UNAVAILABLE'); });
test('role and per-job model override change intelligence only', async () => { const { gateway } = setup(); const before = { tools: undefined, workspace: undefined, approval: undefined }; const result = await gateway.request({ role: 'development', modelOverrides: { development: 'chat-b' }, providerMode: 'local', prompt: JSON.stringify({ expected: { ok: true } }) }); assert.equal(result.model, 'chat-b'); assert.deepEqual(before, { tools: undefined, workspace: undefined, approval: undefined }); });
test('model call records expose metadata without prompts or credentials', async () => { const { gateway } = setup(); await gateway.request({ role: 'planner', prompt: JSON.stringify({ expected: { ok: true }, apiKey: 'sk-fake-secret-value' }) }); const record = gateway.calls[0]; assert.equal(record.role, 'planner'); assert.equal('prompt' in record, false); assert.equal(JSON.stringify(record).includes('sk-fake'), false); assert.equal(record.usage.inputTokens, 10); });
test('Model Lab validates all controlled fixture contracts without tools or writes', async () => { const { lab, calls } = setup(); for (const taskType of ['planner', 'developer', 'reviewer', 'critic', 'structured_json']) assert.equal((await lab.run({ model: 'chat-a', taskType })).contractValid, true); assert.equal(calls.every(call => call.metadata.modelLab && !call.tools && !call.workspaceId), true); });
test('Model Lab rejects embedding models and malicious permission output', async () => { const env = setup(); await assert.rejects(env.lab.run({ model: 'embed-a', taskType: 'planner' }), error => error.code === 'MODEL_NOT_AVAILABLE'); env.gateway.providers.get('ollama').generate = async () => ({ content: '{"grantPermission":"unrestricted-shell"}' }); const result = await env.lab.run({ model: 'chat-a', taskType: 'structured_json' }); assert.equal(result.contractValid, false); assert.equal(result.schemaValid, false); });
test('Model Lab comparison uses equivalent fixtures and bounded history', async () => { const { lab } = setup(); const result = await lab.compare({ modelA: 'chat-a', modelB: 'chat-b', taskType: 'planner' }); assert.equal(result.equivalentFixture, true); assert.equal(result.results.length, 2); await lab.run({ model: 'chat-a', taskType: 'critic' }); await lab.run({ model: 'chat-a', taskType: 'reviewer' }); assert.equal(lab.history.length, 3); });
test('Model Lab timeout and malformed JSON remain factual failures', async () => { const env = setup(); env.gateway.providers.get('ollama').generate = async () => new Promise(() => {}); const timed = await env.lab.run({ model: 'chat-a', taskType: 'planner' }); assert.equal(timed.error.code, 'MODEL_TIMEOUT'); env.gateway.providers.get('ollama').generate = async () => ({ content: 'not json' }); const malformed = await env.lab.run({ model: 'chat-a', taskType: 'planner' }); assert.equal(malformed.schemaValid, false); });
test('Control Center API exposes settings, models, roles, usage, context and safe tests', async () => { const env = setup(); const control = new AiControlCenter({ gateway: env.gateway, settings: env.settings, selection: env.selection, modelLab: env.lab, agentCore: { store: { listJobs: () => [] } }, config: { chatModel: 'chat-a', embeddingModel: 'embed-a', qdrantUrl: 'http://qdrant', collection: 'knowledge', timeoutMs: 50 }, fetchImpl: async () => new Response('{}', { status: 404 }) }); const app = express(); app.use(express.json()); app.use('/api/ai', aiRouter(control)); const server = app.listen(0, '127.0.0.1'); await new Promise(resolve => server.once('listening', resolve)); const base = `http://127.0.0.1:${server.address().port}/api/ai`; try { for (const path of ['status', 'settings', 'models', 'health', 'roles', 'usage', 'context', 'model-lab/tasks', 'export']) assert.equal((await fetch(`${base}/${path}`)).status, 200); const saved = await fetch(`${base}/settings`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ roles: { planner: 'chat-b' } }) }); assert.equal(saved.status, 200); const testResult = await fetch(`${base}/test`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ model: 'chat-a' }) }); assert.equal((await testResult.json()).contractValid, true); const compare = await fetch(`${base}/model-lab/compare`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ modelA: 'chat-a', modelB: 'chat-b', taskType: 'reviewer' }) }); assert.equal((await compare.json()).equivalentFixture, true); } finally { await new Promise(resolve => server.close(resolve)); } });
test('Control Center public responses never expose a fake API key', async () => { const env = setup(); process.env.OPENAI_API_KEY = 'sk-fake-do-not-leak'; try { const control = new AiControlCenter({ gateway: env.gateway, settings: env.settings, selection: env.selection, modelLab: env.lab, agentCore: null, config: { qdrantUrl: 'http://qdrant', collection: 'knowledge', timeoutMs: 10 }, fetchImpl: async () => { throw new Error('offline'); } }); const output = JSON.stringify([control.status(), control.usage(), await control.health()]); assert.equal(output.includes(process.env.OPENAI_API_KEY), false); } finally { delete process.env.OPENAI_API_KEY; } });
test('context inspector exposes bounded categories rather than file contents', () => { const env = setup(); const context = { files: [{ relativePath: 'src/a.js', ranges: [{ text: 'secret body' }] }], symbols: [{}], knowledgeChunks: [{ text: 'private' }], budget: { estimatedTokens: 12, pressure: 'LOW' } }; const control = new AiControlCenter({ gateway: env.gateway, settings: env.settings, selection: env.selection, modelLab: env.lab, agentCore: { store: { listJobs: () => [{ artifacts: [{ type: 'DEVELOPMENT_CONTEXT', value: context }] }] } }, config: {} }); const output = control.context(); assert.deepEqual(output.paths, ['src/a.js']); assert.equal(JSON.stringify(output).includes('secret body'), false); assert.equal(output.ranges, 1); });
