import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, readFile, mkdir, rm, symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import express from 'express';
import { WorkspaceRegistry, contentHash } from '../src/development/workspaceRegistry.js';
import { parsePatchProposal, patchFingerprint } from '../src/development/patchProposal.js';
import { TestCommandRegistry } from '../src/development/testCommandRegistry.js';
import { createPatchSafetyEvaluator } from '../src/evaluation/patchSafetyEvaluator.js';
import { createAgentCore, agentRouter } from '../src/core/agentRouter.js';
import { ModelRegistry } from '../src/models/modelRegistry.js';
import { ModelGateway } from '../src/models/modelGateway.js';

const projectId = 'Phase6Test';
const makeRoot = async () => mkdtemp(path.join(tmpdir(), 'darkcry-phase6-'));
const command = (id = 'test') => ({ id, executable: 'node', args: ['test.mjs'], timeoutMs: 5000 });
const request = (workspaceId, overrides = {}) => ({ projectId, workspaceId, request: 'Fix add() so the test passes.', acceptanceCriteria: ['add(2,3) is 5'], allowedPaths: ['src', 'test.mjs'], deniedPaths: [], testCommandIds: ['test'], contextFiles: ['src/add.mjs'], maxFilesChanged: 3, maxPatchBytes: 20000, maxIterations: 2, allowCreateFiles: true, allowDeleteFiles: false, allowGitRead: true, allowGitWrite: false, dryRun: false, ...overrides });
const proposal = (baseHash, content = 'export const add = (a, b) => a + b;\n', extra = {}) => ({ summary: 'Fix add', reasoningSummary: 'Correct the operator.', files: [{ path: 'src/add.mjs', operation: 'MODIFY', content, baseHash, purpose: 'Fix arithmetic' }], testsRecommended: ['test'], risks: [], assumptions: [], ...extra });
async function fixture({ responses = null } = {}) {
  const root = await makeRoot(); await mkdir(path.join(root, 'src')); await writeFile(path.join(root, 'src', 'add.mjs'), 'export const add = (a, b) => a - b;\n'); await writeFile(path.join(root, 'test.mjs'), "import assert from 'node:assert/strict'; import { add } from './src/add.mjs'; assert.equal(add(2,3),5);\n");
  const workspaces = new WorkspaceRegistry({ snapshotRoot: path.join(root, '.snapshots'), maxReadBytes: 10000 }); const ws = await workspaces.register({ projectId, root, allowedPaths: ['src', 'test.mjs'], testCommands: [command()] });
  let calls = 0; const provider = { id: 'fake', capabilities: ['chat'], async health() { return true; }, async embed() { return []; }, async generate({ messages }) { calls++; const input = JSON.parse(messages[0].content), file = input.files[0]; const custom = responses?.[calls - 1]; return { content: JSON.stringify(custom ? custom(file, input) : proposal(file.baseHash)), usage: {} }; } };
  const registry = new ModelRegistry(); registry.register({ modelId: 'fake-dev', providerId: 'fake', capabilities: ['chat'], purposes: ['GENERAL', 'REPAIR'], enabled: true }); const models = new ModelGateway({ registry }); models.registerProvider(provider);
  const core = createAgentCore({ models, workspaces, testCommands: new TestCommandRegistry() });
  return { root, workspaces, ws, core, calls: () => calls, cleanup: () => rm(root, { recursive: true, force: true }) };
}

test('workspace registration, bounded read/list/search, size and secret/binary rules', async () => {
  const root = await makeRoot(), workspaces = new WorkspaceRegistry({ maxReadBytes: 10 }); try {
    await writeFile(path.join(root, 'a.txt'), 'needle'); await writeFile(path.join(root, '.env'), 'SECRET=x'); await writeFile(path.join(root, 'image.png'), 'x'); await writeFile(path.join(root, 'large.txt'), 'x'.repeat(20));
    const ws = await workspaces.register({ projectId, root }); assert.ok(ws.workspaceId); assert.equal((await workspaces.list({ workspaceId: ws.workspaceId })).entries.some(item => item.name === '.env'), false);
    assert.equal((await workspaces.read({ workspaceId: ws.workspaceId, relativePath: 'a.txt' })).text, 'needle'); assert.equal((await workspaces.search({ workspaceId: ws.workspaceId, query: 'needle' })).results.length, 1);
    await assert.rejects(workspaces.read({ workspaceId: ws.workspaceId, relativePath: '.env' }), { code: 'PATH_DENIED' }); await assert.rejects(workspaces.read({ workspaceId: ws.workspaceId, relativePath: 'image.png' }), { code: 'BINARY_FILE_DENIED' }); await assert.rejects(workspaces.read({ workspaceId: ws.workspaceId, relativePath: 'large.txt' }), { code: 'FILE_TOO_LARGE' });
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('path traversal, absolute outside path, denied path and link escape are blocked', async t => {
  const root = await makeRoot(), outside = await makeRoot(), workspaces = new WorkspaceRegistry(); try { await writeFile(path.join(outside, 'outside.txt'), 'x'); const ws = await workspaces.register({ projectId, root, deniedPaths: ['private'] });
    await assert.rejects(workspaces.resolve(ws.workspaceId, '../outside.txt'), { code: 'PATH_OUTSIDE_WORKSPACE' }); await assert.rejects(workspaces.resolve(ws.workspaceId, path.join(outside, 'outside.txt')), { code: 'PATH_OUTSIDE_WORKSPACE' }); await assert.rejects(workspaces.resolve(ws.workspaceId, 'private/x.txt'), { code: 'PATH_DENIED' });
    try { await symlink(outside, path.join(root, 'link'), 'junction'); await assert.rejects(workspaces.read({ workspaceId: ws.workspaceId, relativePath: 'link/outside.txt' }), { code: 'PATH_OUTSIDE_WORKSPACE' }); await assert.rejects(workspaces.resolve(ws.workspaceId, 'link/new/file.txt'), { code: 'PATH_OUTSIDE_WORKSPACE' }); } catch (error) { if (error.code === 'EPERM') t.diagnostic('junction fixture skipped: privilege unavailable'); else throw error; }
  } finally { await rm(root, { recursive: true, force: true }); await rm(outside, { recursive: true, force: true }); }
});

test('patch parser and stable fingerprint enforce structured full-content proposal', () => { const p = proposal('a'.repeat(64)); assert.deepEqual(parsePatchProposal(JSON.stringify(p)), p); assert.equal(patchFingerprint(p), patchFingerprint({ ...p })); assert.throws(() => parsePatchProposal('bad'), { code: 'PATCH_INVALID' }); });

test('patch safety enforces count, byte, delete, create, path and suspicious-code policies', async () => { const root = await makeRoot(), workspaces = new WorkspaceRegistry(); try { const ws = await workspaces.register({ projectId, root, allowedPaths: ['src'] }), evaluator = createPatchSafetyEvaluator(workspaces), scope = { development: request(ws.workspaceId, { maxFilesChanged: 1, maxPatchBytes: 200, allowCreateFiles: false }) }; const bad = { data: { proposal: { ...proposal('a'.repeat(64)), files: [{ path: '../x', operation: 'DELETE', content: null, baseHash: 'a'.repeat(64), purpose: '' }, { path: 'src/a.js', operation: 'CREATE', content: 'child_process.execSync("x")', baseHash: null, purpose: '' }] } } }; const result = evaluator.evaluate({ result: bad, context: { task: { scope } } }); assert.equal(result.status, 'fail'); assert.ok(new Set(result.issues.map(item => item.type)).has('PATH_OUTSIDE_WORKSPACE')); assert.ok(result.issues.some(item => item.type === 'SUSPICIOUS_CODE')); } finally { await rm(root, { recursive: true, force: true }); } });

test('apply creates snapshot, detects stale patch, supports create/delete and rollback', async () => { const root = await makeRoot(), workspaces = new WorkspaceRegistry({ snapshotRoot: path.join(root, '.snap') }); try { await writeFile(path.join(root, 'a.txt'), 'old'); const ws = await workspaces.register({ projectId, root }); const p = { ...proposal(contentHash('old')), files: [{ path: 'a.txt', operation: 'MODIFY', content: 'new', baseHash: contentHash('old'), purpose: '' }, { path: 'b.txt', operation: 'CREATE', content: 'created', baseHash: null, purpose: '' }] }, f = patchFingerprint(p); const applied = await workspaces.apply({ workspaceId: ws.workspaceId, proposal: p, patchFingerprint: f, expectedFingerprint: f, allowCreateFiles: true, allowDeleteFiles: false }); assert.equal(await readFile(path.join(root, 'a.txt'), 'utf8'), 'new'); await workspaces.restore(applied.snapshotId); assert.equal(await readFile(path.join(root, 'a.txt'), 'utf8'), 'old'); await assert.rejects(readFile(path.join(root, 'b.txt'))); await writeFile(path.join(root, 'a.txt'), 'human'); await assert.rejects(workspaces.apply({ workspaceId: ws.workspaceId, proposal: p, patchFingerprint: f, expectedFingerprint: f, allowCreateFiles: true, allowDeleteFiles: false }), { code: 'STALE_PATCH' }); const del = { ...proposal(contentHash('human')), files: [{ path: 'a.txt', operation: 'DELETE', content: null, baseHash: contentHash('human'), purpose: '' }] }; await assert.rejects(workspaces.apply({ workspaceId: ws.workspaceId, proposal: del, patchFingerprint: patchFingerprint(del), expectedFingerprint: patchFingerprint(del), allowDeleteFiles: false }), { code: 'DELETE_NOT_ALLOWED' }); const gone = await workspaces.apply({ workspaceId: ws.workspaceId, proposal: del, patchFingerprint: patchFingerprint(del), expectedFingerprint: patchFingerprint(del), allowDeleteFiles: true }); await assert.rejects(readFile(path.join(root, 'a.txt'))); await workspaces.restore(gone.snapshotId); assert.equal(await readFile(path.join(root, 'a.txt'), 'utf8'), 'human'); } finally { await rm(root, { recursive: true, force: true }); } });

test('multi-file controlled failure rolls back every applied file', async () => { const root = await makeRoot(), workspaces = new WorkspaceRegistry({ snapshotRoot: path.join(root, '.snap') }); try { await writeFile(path.join(root, 'a.txt'), 'a'); await writeFile(path.join(root, 'b.txt'), 'b'); const ws = await workspaces.register({ projectId, root }), p = { ...proposal(contentHash('a')), files: [{ path: 'a.txt', operation: 'MODIFY', content: 'A', baseHash: contentHash('a'), purpose: '' }, { path: 'b.txt', operation: 'MODIFY', content: 'B', baseHash: contentHash('b'), purpose: '' }] }, f = patchFingerprint(p); await assert.rejects(workspaces.apply({ workspaceId: ws.workspaceId, proposal: p, patchFingerprint: f, expectedFingerprint: f, simulateFailureAfter: 1 }), { code: 'PATCH_APPLY_FAILED' }); assert.equal(await readFile(path.join(root, 'a.txt'), 'utf8'), 'a'); assert.equal(await readFile(path.join(root, 'b.txt'), 'utf8'), 'b'); } finally { await rm(root, { recursive: true, force: true }); } });

test('test registry rejects shell attacks, bounds output and reports failure/timeout', async () => { const root = await makeRoot(), registry = new TestCommandRegistry(); try { assert.throws(() => registry.validate({ id: 'bad', executable: 'npm', args: ['test && del x'], timeoutMs: 1000 }), { code: 'TEST_COMMAND_NOT_ALLOWED' }); assert.throws(() => registry.validate({ id: 'bad', executable: 'powershell', args: ['-Command', 'x'], timeoutMs: 1000 }), { code: 'TEST_COMMAND_NOT_ALLOWED' }); assert.throws(() => registry.validate({ id: 'bad', executable: 'node', args: ['-e', 'process.exit()'], timeoutMs: 1000 }), { code: 'TEST_COMMAND_NOT_ALLOWED' }); await writeFile(path.join(root, 'fail.mjs'), 'console.log("x".repeat(100));process.exit(2);'); await writeFile(path.join(root, 'hang.mjs'), 'setInterval(()=>{},1000);'); const workspace = { canonicalRoot: root, testCommands: [{ id: 'fail', executable: 'node', args: ['fail.mjs'], timeoutMs: 1000 }, { id: 'hang', executable: 'node', args: ['hang.mjs'], timeoutMs: 50 }] }; const failed = await registry.run(workspace, 'fail', { outputLimit: 20 }); assert.equal(failed.code, 'TEST_FAILED'); assert.equal(failed.truncated, true); const timeout = await registry.run(workspace, 'hang'); assert.equal(timeout.code, 'TEST_TIMEOUT'); } finally { await rm(root, { recursive: true, force: true }); } });

test('dry run proposes, evaluates and reviews without writing', async () => { const f = await fixture(); try { const dev = request(f.ws.workspaceId, { dryRun: true }); const job = f.core.createJob(dev.request, { projectId, kind: 'development', maxIterations: 2, metadata: { development: dev } }); const result = await f.core.run(job.jobId); assert.equal(result.status, 'COMPLETED'); assert.equal(result.tasks[0].result.data.dryRun, true); assert.equal(await readFile(path.join(f.root, 'src', 'add.mjs'), 'utf8'), 'export const add = (a, b) => a - b;\n'); assert.equal(result.approvals.length, 0); } finally { await f.cleanup(); } });

test('exact human approval applies patch, runs registered test, records artifacts and events', async () => { const f = await fixture(); try { const dev = request(f.ws.workspaceId), job = f.core.createJob(dev.request, { projectId, kind: 'development', maxIterations: 2, metadata: { development: dev } }); const pending = await f.core.run(job.jobId); assert.equal(pending.status, 'WAITING_FOR_APPROVAL'); assert.equal(await readFile(path.join(f.root, 'src', 'add.mjs'), 'utf8'), 'export const add = (a, b) => a - b;\n'); assert.ok(pending.approvals[0].requestPreview.fingerprint); const done = await f.core.approve(pending.approvals[0].approvalId); assert.equal(done.status, 'COMPLETED'); assert.ok(done.artifacts.some(item => item.type === 'TEST_RESULT')); assert.ok(done.events.some(item => item.type === 'PATCH_APPLIED')); assert.match(await readFile(path.join(f.root, 'src', 'add.mjs'), 'utf8'), /a \+ b/); } finally { await f.cleanup(); } });

test('approval for Patch A cannot apply Patch B', async () => { const f = await fixture(); try { const dev = request(f.ws.workspaceId, { maxIterations: 1 }), job = f.core.createJob(dev.request, { projectId, kind: 'development', maxIterations: 1, metadata: { development: dev } }); const pending = await f.core.run(job.jobId), task = f.core.getJob(job.jobId).tasks[0]; task.pendingState.proposal.files[0].content = 'export const add = () => 999;\n'; const result = await f.core.approve(pending.approvals[0].approvalId); assert.equal(result.status, 'FAILED'); assert.equal(result.tasks[0].result.data.applyError.code, 'APPROVAL_SCOPE_MISMATCH'); assert.match(await readFile(path.join(f.root, 'src', 'add.mjs'), 'utf8'), /a - b/); } finally { await f.cleanup(); } });

test('failed first patch enters critic repair and requires a new approval before passing', async () => { const f = await fixture({ responses: [(file) => proposal(file.baseHash, 'export const add = (a, b) => a * b;\n'), (file) => proposal(file.baseHash)] }); try { const dev = request(f.ws.workspaceId), job = f.core.createJob(dev.request, { projectId, kind: 'development', maxIterations: 2, metadata: { development: dev } }); let result = await f.core.run(job.jobId); assert.equal(result.status, 'WAITING_FOR_APPROVAL'); result = await f.core.approve(result.approvals.at(-1).approvalId); assert.equal(result.status, 'WAITING_FOR_APPROVAL'); assert.equal(result.approvals.length, 2); assert.ok(result.events.some(item => item.type === 'REPAIR_GUIDANCE_CREATED')); result = await f.core.approve(result.approvals.at(-1).approvalId); assert.equal(result.status, 'COMPLETED'); assert.equal(f.calls(), 2); } finally { await f.cleanup(); } });

test('repeated failed repair detects no progress and rolls approved writes back to baseline', async () => { const wrong = file => proposal(file.baseHash, 'export const add = (a, b) => a * b;\n'); const f = await fixture({ responses: [wrong, wrong] }); try { const dev = request(f.ws.workspaceId, { maxIterations: 3 }), job = f.core.createJob(dev.request, { projectId, kind: 'development', maxIterations: 3, metadata: { development: dev } }); let result = await f.core.run(job.jobId); result = await f.core.approve(result.approvals.at(-1).approvalId); assert.equal(result.status, 'WAITING_FOR_APPROVAL'); result = await f.core.approve(result.approvals.at(-1).approvalId); assert.equal(result.status, 'FAILED'); assert.ok(result.events.some(item => item.type === 'NO_PROGRESS_DETECTED')); assert.ok(result.events.some(item => item.type === 'DEVELOPMENT_ROLLBACK_COMPLETED')); assert.match(await readFile(path.join(f.root, 'src', 'add.mjs'), 'utf8'), /a - b/); } finally { await f.cleanup(); } });

test('development API validates input and denial performs no write', async () => { const f = await fixture(); const app = express(); app.use(express.json()); app.use('/api/agent', agentRouter(f.core)); const server = app.listen(0, '127.0.0.1'); await new Promise(resolve => server.once('listening', resolve)); try { const base = `http://127.0.0.1:${server.address().port}/api/agent`; const invalid = await fetch(`${base}/development/jobs`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); assert.equal(invalid.status, 400); const body = { projectId, workspaceRoot: f.root, request: 'Fix add', acceptanceCriteria: ['passes'], allowedPaths: ['src', 'test.mjs'], deniedPaths: [], testCommands: [command()], contextFiles: ['src/add.mjs'] }; const created = await (await fetch(`${base}/development/jobs`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) })).json(); const pending = await (await fetch(`${base}/development/jobs/${created.jobId}/run`, { method: 'POST' })).json(); const denied = await (await fetch(`${base}/approvals/${pending.approvals[0].approvalId}/deny`, { method: 'POST' })).json(); assert.equal(denied.status, 'BLOCKED'); assert.match(await readFile(path.join(f.root, 'src', 'add.mjs'), 'utf8'), /a - b/); } finally { await new Promise(resolve => server.close(resolve)); await f.cleanup(); } });
