import path from 'node:path';
import { fingerprint, validateDocumentIR } from '../documents/documentCore.js';
import { renderDocx, validateDocx } from '../documents/docxRenderer.js';

const definitions = [
  ['plan', 'DOCUMENT_PLAN', 'Document plan', 'document.planner'], ['research', 'DOCUMENT_RESEARCH', 'Source research', 'document.research'], ['evidence', 'EVIDENCE_BUILD', 'Evidence pack', 'document.evidence'], ['draft', 'DOCUMENT_DRAFT', 'Document draft', 'document.writer'], ['grounding', 'GROUNDING_CHECK', 'Fact check', 'document.factChecker'], ['review', 'DOCUMENT_REVIEW', 'Document review', 'document.reviewer'], ['qa', 'DOCUMENT_QA', 'Deterministic QA', 'document.qa'], ['approval', 'DOCUMENT_APPROVAL', 'Human approval', 'document.approval'], ['render', 'DOCUMENT_RENDER', 'DOCX render', 'document.renderer'], ['artifactQa', 'ARTIFACT_QA', 'Artifact QA', 'document.artifactQa'], ['final', 'FINAL_REVIEW', 'Final review', 'document.finalReviewer']
];
const result = (summary, data, artifacts = []) => ({ status: 'completed', summary, data, artifacts });

export class DocumentTaskGraph {
  constructor(core, { root }) { this.core = core; this.root = root; }
  async validateApproval(job, approval) { const expected = (await import('../tools/approvalService.js')).inputDigest({ projectId: job.projectId, fingerprint: job.documentState.fingerprint, revision: job.documentState.revision }); if (approval.inputDigest !== expected) throw Object.assign(new Error('Approved document revision changed.'), { code: 'STALE_DOCUMENT_APPROVAL', status: 409 }); }
  tasks(job) { const ids = new Map(definitions.map(item => [item[0], crypto.randomUUID()])); return definitions.map((item, index) => ({ taskId: ids.get(item[0]), jobId: job.jobId, projectId: job.projectId, key: item[0], type: item[1], title: item[2], objective: item[2], assignedAgent: item[3], dependencies: index ? [ids.get(definitions[index - 1][0])] : [], requiredInputs: [], expectedOutputs: [], acceptanceCriteria: [{ type: 'fieldExists', field: 'summary' }], evaluatorId: 'deterministic', allowedTools: [], scope: {}, contextBudget: { maxInputTokens: 6000, maxRetrievedSources: 30 }, timeout: 30000, status: 'QUEUED', priority: 0, attempt: 0, maxAttempts: 2, result: null, issues: [], validations: [], runs: [], repairGuidance: null, pendingApprovalId: null, pendingState: null, failureReason: null, createdAt: new Date().toISOString(), startedAt: null, completedAt: null })); }
  async stage(job, key, execute) { const task = job.tasks.find(item => item.key === key); this.core.change(job, task, 'PLANNING'); this.core.change(job, task, 'READY'); task.attempt++; this.core.change(job, task, 'RUNNING'); const output = await execute(task); task.result = output; for (const artifact of output.artifacts || []) this.core.artifacts.register({ job, task, agentId: task.assignedAgent, output: artifact }); this.core.change(job, task, 'VALIDATING'); this.core.change(job, task, 'COMPLETED'); return output.data; }
  async extra(job, key, type, title, assignedAgent, execute) { const task = { taskId: crypto.randomUUID(), jobId: job.jobId, projectId: job.projectId, key, type, title, objective: title, assignedAgent, dependencies: [], requiredInputs: [], expectedOutputs: [], acceptanceCriteria: [{ type: 'fieldExists', field: 'summary' }], evaluatorId: 'deterministic', allowedTools: [], scope: {}, contextBudget: { maxInputTokens: 6000, maxRetrievedSources: 30 }, timeout: 30000, status: 'QUEUED', priority: 0, attempt: 0, maxAttempts: 1, result: null, issues: [], validations: [], runs: [], createdAt: new Date().toISOString(), startedAt: null, completedAt: null }; job.tasks.splice(job.tasks.findIndex(item => item.key === 'approval'), 0, task); this.core.change(job, task, 'PLANNING'); this.core.change(job, task, 'READY'); task.attempt++; this.core.change(job, task, 'RUNNING'); const output = await execute(task); task.result = output; for (const artifact of output.artifacts || []) this.core.artifacts.register({ job, task, agentId: assignedAgent, output: artifact }); this.core.change(job, task, 'VALIDATING'); this.core.change(job, task, 'COMPLETED'); return output.data; }
  async start(job) { const request = job.metadata.document; job.tasks = this.tasks(job); job.documentState = { revision: 1, revisions: [], metrics: { evidenceItems: 0, evidenceTokens: 0, draftTokens: 0, retries: 0, pressure: 'NORMAL' } }; this.core.change(job, job, 'PLANNING'); this.core.change(job, job, 'READY'); this.core.change(job, job, 'RUNNING');
    const base = task => ({ request, projectId: job.projectId, jobId: job.jobId, taskId: task.taskId });
    const plan = await this.stage(job, 'plan', task => this.core.agents.get('document.planner').execute(base(task))); const research = await this.stage(job, 'research', task => this.core.agents.get('document.research').execute(base(task))); const evidence = await this.stage(job, 'evidence', task => this.core.agents.get('document.evidence').execute({ ...base(task), records: research.records, specification: plan.specification })); job.documentState.metrics = { ...job.documentState.metrics, evidenceItems: evidence.evidencePack.items.length, evidenceTokens: evidence.evidencePack.estimatedTokens, pressure: evidence.evidencePack.pressure };
    let draft = await this.stage(job, 'draft', task => this.core.agents.get('document.writer').execute({ ...base(task), specification: plan.specification, evidencePack: evidence.evidencePack, revision: 1 })); let grounding = await this.stage(job, 'grounding', task => this.core.agents.get('document.factChecker').execute({ ...base(task), specification: plan.specification, evidencePack: evidence.evidencePack, ir: draft.ir })); let review = await this.stage(job, 'review', task => this.core.agents.get('document.reviewer').execute({ ...base(task), specification: plan.specification, ir: draft.ir })); let qa = await this.stage(job, 'qa', async () => result('Deterministic document QA completed.', { qa: validateDocumentIR(draft.ir, plan.specification, evidence.evidencePack) }, [{ type: 'DOCUMENT_QA', value: validateDocumentIR(draft.ir, plan.specification, evidence.evidencePack) }]));
    let irFingerprint = fingerprint(draft.ir); job.documentState = { ...job.documentState, specification: plan.specification, evidencePack: evidence.evidencePack, ir: draft.ir, qa: qa.qa, review, grounding: grounding.grounding, fingerprint: irFingerprint, revisions: [{ revision: 1, fingerprint: irFingerprint, grounding: grounding.grounding.status, review: review.status, qa: qa.qa.status }] }; job.documentState.metrics.draftTokens = Math.ceil(JSON.stringify(draft.ir).length / 4);
    let combinedIssues = [...grounding.grounding.issues, ...review.issues, ...qa.qa.issues]; if (combinedIssues.length) { const critique = await this.extra(job, 'critic-1', 'DOCUMENT_CRITIC', 'Document critic', 'document.critic', task => this.core.agents.get('document.critic').execute({ ...base(task), issues: combinedIssues, attempt: 1 })); const revised = await this.extra(job, 'revise-2', 'DOCUMENT_REVISE', 'Targeted document revision', 'document.writer', task => this.core.agents.get('document.writer').execute({ ...base(task), specification: plan.specification, evidencePack: evidence.evidencePack, revision: 2, feedback: critique })); const revisedFingerprint = fingerprint(revised.ir); job.documentState.metrics.retries = 1; if (revisedFingerprint === irFingerprint) { job.failureReason = `NO_PROGRESS:${combinedIssues.map(item => item.type).join(',')}`; job.documentState.noProgress = { detected: true, fingerprint: irFingerprint, issues: combinedIssues.map(item => item.type) }; this.core.change(job, job, 'FAILED'); this.core.store.saveJob(job); return this.core.details(job.jobId); } draft = revised; irFingerprint = revisedFingerprint; grounding = await this.extra(job, 'grounding-2', 'GROUNDING_CHECK', 'Revision fact check', 'document.factChecker', task => this.core.agents.get('document.factChecker').execute({ ...base(task), specification: plan.specification, evidencePack: evidence.evidencePack, ir: draft.ir })); review = await this.extra(job, 'review-2', 'DOCUMENT_REVIEW', 'Revision review', 'document.reviewer', task => this.core.agents.get('document.reviewer').execute({ ...base(task), specification: plan.specification, ir: draft.ir })); qa = await this.extra(job, 'qa-2', 'DOCUMENT_QA', 'Revision deterministic QA', 'document.qa', async () => result('Revision QA completed.', { qa: validateDocumentIR(draft.ir, plan.specification, evidence.evidencePack) }, [{ type: 'DOCUMENT_QA', value: validateDocumentIR(draft.ir, plan.specification, evidence.evidencePack) }])); combinedIssues = [...grounding.grounding.issues, ...review.issues, ...qa.qa.issues]; job.documentState.revision = 2; job.documentState.ir = draft.ir; job.documentState.fingerprint = revisedFingerprint; job.documentState.qa = qa.qa; job.documentState.review = review; job.documentState.grounding = grounding.grounding; job.documentState.revisions.push({ revision: 2, fingerprint: revisedFingerprint, grounding: grounding.grounding.status, review: review.status, qa: qa.qa.status }); if (combinedIssues.length) { job.failureReason = `REVISION_LIMIT:${combinedIssues.map(item => item.type).join(',')}`; this.core.change(job, job, 'FAILED'); this.core.store.saveJob(job); return this.core.details(job.jobId); } }
    const task = job.tasks.find(item => item.key === 'approval'); this.core.change(job, task, 'PLANNING'); this.core.change(job, task, 'READY'); this.core.change(job, task, 'RUNNING'); const approval = this.core.approvals.create({ job, task, agent: { id: 'document.approval' }, tool: { id: 'document.render', riskLevel: 'CONTROLLED' }, action: 'render-approved-document', input: { projectId: job.projectId, fingerprint: irFingerprint, revision: 1 }, reason: 'Approve the exact grounded Document IR before final DOCX rendering.' }); approval.requestPreview = { summary: draft.ir.metadata.title, fingerprint: irFingerprint, revision: 1, sections: draft.ir.sections.map(section => section.heading), grounding: grounding.grounding.status, review: review.status, qa: qa.qa.status, unsupported: combinedIssues }; task.pendingApprovalId = approval.approvalId; task.approvalReturnState = 'RUNNING'; this.core.change(job, task, 'WAITING_FOR_APPROVAL'); job.approvalReturnState = 'RUNNING'; this.core.change(job, job, 'WAITING_FOR_APPROVAL'); this.core.store.saveJob(job); return this.core.details(job.jobId);
  }
  async continue(job, task) { const state = job.documentState, approval = this.core.approvals.get(task.pendingApprovalId); await this.validateApproval(job, approval); approval.consumedAt = new Date().toISOString(); task.pendingApprovalId = null; this.core.change(job, task, 'VALIDATING'); this.core.change(job, task, 'COMPLETED'); const outputDir = path.join(this.root, 'data', 'artifacts', job.projectId, job.metadata.document.missionId, job.metadata.document.runId);
    const rendered = await this.stage(job, 'render', async () => { const file = await renderDocx({ ir: state.ir, outputDir, filename: state.specification.title }); return result('Approved DOCX rendered.', { file }, [{ type: 'DOCUMENT_FILE', path: file.path, value: { ...file, path: undefined, projectId: job.projectId, missionId: job.metadata.document.missionId, runId: job.metadata.document.runId, revision: state.revision, irFingerprint: state.fingerprint, createdAt: new Date().toISOString() } }]); }); const artifactQa = await this.stage(job, 'artifactQa', async () => { const qa = await validateDocx(rendered.file.path, [state.specification.title, state.ir.sections[0].heading]); return result('DOCX structural QA completed.', { artifactQa: qa }, [{ type: 'DOCUMENT_ARTIFACT_QA', value: qa }]); }); const final = await this.stage(job, 'final', task => this.core.agents.get('document.finalReviewer').execute({ request: job.metadata.document, projectId: job.projectId, jobId: job.jobId, taskId: task.taskId, qa: state.qa, artifactQa: artifactQa.artifactQa, approval })); job.finalReview = { status: 'completed', summary: final.passed ? 'Final document review passed.' : 'Final document review failed.', data: final }; if (final.passed) { this.core.change(job, job, 'VALIDATING'); this.core.change(job, job, 'COMPLETED'); } else this.core.change(job, job, 'FAILED'); this.core.store.saveJob(job); return this.core.details(job.jobId); }
}
