import { createHash, randomUUID } from 'node:crypto';

export const DOCUMENT_TYPES = ['REPORT', 'ACCOMPLISHMENT_REPORT', 'TECHNICAL_REPORT', 'EXECUTIVE_SUMMARY', 'RESEARCH_BRIEF', 'MEMO', 'LETTER', 'GENERAL_DOCUMENT'];
export const BLOCK_TYPES = ['paragraph', 'bullet_list', 'numbered_list', 'table', 'callout', 'signature_block', 'page_break'];
const text = (value, max, fallback = '') => typeof value === 'string' && value.trim() && value.length <= max && !value.includes('\0') ? value.trim() : fallback;
const array = (value, max) => Array.isArray(value) ? value.slice(0, max) : [];
export const fingerprint = value => createHash('sha256').update(JSON.stringify(value, (key, item) => ['generatedAt', 'createdAt'].includes(key) ? undefined : item)).digest('hex');
export const safeFilename = value => { let name = String(value || 'document').normalize('NFKD').replace(/[^A-Za-z0-9._ -]+/g, '_').replace(/[\s_]+/g, '_').replace(/\.{2,}/g, '.').replace(/^[. _]+|[. _]+$/g, '').slice(0, 100) || 'document'; if (/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(name)) name = `document_${name}`; return `${name.replace(/\.docx$/i, '')}.docx`; };

export function validateSpecification(input = {}, request = '') {
  const documentType = String(input.documentType || 'GENERAL_DOCUMENT').toUpperCase(); if (!DOCUMENT_TYPES.includes(documentType)) throw Object.assign(new Error('Invalid document type.'), { code: 'DOCUMENT_SPEC_INVALID' });
  const output = String(input.output || 'DOCX').toUpperCase(); if (output !== 'DOCX') throw Object.assign(new Error('Only DOCX output is available.'), { code: 'DOCUMENT_OUTPUT_INVALID' });
  if (Array.isArray(input.sections) && input.sections.length > 20) throw Object.assign(new Error('Too many document sections.'), { code: 'DOCUMENT_SPEC_BOUNDS' }); const sections = array(input.sections, 20).map((item, index) => text(typeof item === 'string' ? item : item?.heading, 120, `Section ${index + 1}`));
  return { documentType, title: text(input.title, 180, text(request, 180, 'Project Document')), purpose: text(input.purpose, 500, text(request, 500)), audience: text(input.audience, 120, 'Project stakeholders'), language: ['English', 'Filipino', 'Taglish'].includes(input.language) ? input.language : 'English', tone: text(input.tone, 80, 'Professional'), period: text(input.period, 100), style: ['PROFESSIONAL', 'GOVERNMENT_REPORT', 'MINIMAL'].includes(String(input.style || '').toUpperCase()) ? String(input.style).toUpperCase() : 'PROFESSIONAL', sections: sections.length ? sections : ['Executive Summary', 'Accomplishments', 'Sources'], requiredFacts: array(input.requiredFacts, 30).map(item => text(item, 200)).filter(Boolean), sourcePolicy: 'PROJECT_ONLY', citationStyle: 'SOURCE_NOTES', outputFormats: ['DOCX'], constraints: { maxSections: 20, maxBlocks: 100, maxEvidenceItems: 30, maxRevisions: 2, allowPlaceholders: input.allowPlaceholders === true } };
}

export function buildEvidencePack(records, specification, projectId) {
  const seen = new Set(), items = []; let chars = 0;
  for (const record of records) { const content = text(record.content, 50000); if (!content) continue; for (const raw of content.split(/\n\s*\n|(?<=[.!?])\s+(?=[A-Z0-9])/).slice(0, 50)) { const excerpt = raw.replace(/\s+/g, ' ').trim().slice(0, 1200); if (excerpt.length < 3) continue; const key = excerpt.toLowerCase(); if (seen.has(key) || chars + excerpt.length > 24000 || items.length >= 30) continue; seen.add(key); chars += excerpt.length; items.push({ id: randomUUID(), projectId, sourceId: record.id, sourceType: record.type || 'DOCUMENT', provenance: { filename: record.originalName || record.filename || record.title || 'Project source', ...(record.provenance || {}) }, text: excerpt, relevance: specification.period && excerpt.toLowerCase().includes(specification.period.toLowerCase()) ? 'PERIOD_MATCH' : 'PROJECT_SOURCE', supports: specification.requiredFacts.filter(fact => excerpt.toLowerCase().includes(fact.toLowerCase().split(' ')[0])) }); } }
  const coverage = specification.requiredFacts.map(fact => ({ fact, status: items.some(item => item.text.toLowerCase().includes(fact.toLowerCase())) ? 'SUPPORTED' : items.some(item => fact.toLowerCase().split(/\s+/).some(term => term.length > 4 && item.text.toLowerCase().includes(term))) ? 'PARTIALLY_SUPPORTED' : 'UNSUPPORTED' })); return { projectId, items, coverage, estimatedTokens: Math.ceil(chars / 4), pressure: items.length >= 30 || chars >= 24000 ? 'TRUNCATED' : 'NORMAL' };
}

export function validateDocumentIR(ir, specification, evidencePack) {
  const issues = [], evidence = new Map(evidencePack.items.map(item => [item.id, item])); if (!ir || typeof ir !== 'object' || text(ir.metadata?.title, 180) === '') issues.push({ type: 'TITLE_MISSING', location: 'metadata.title' }); if (!Array.isArray(ir?.sections) || !ir.sections.length || ir.sections.length > 20) issues.push({ type: 'SECTIONS_INVALID', location: 'sections' }); const headings = new Set(), numberGroups = { summary: new Set(), body: new Set() };
  for (const [si, section] of (ir?.sections || []).entries()) { const heading = text(section.heading, 120); if (!heading) issues.push({ type: 'HEADING_MISSING', location: `section:${si}` }); else if (headings.has(heading.toLowerCase())) issues.push({ type: 'DUPLICATE_HEADING', location: heading }); else headings.add(heading.toLowerCase()); if (!Array.isArray(section.blocks) || !section.blocks.length) issues.push({ type: 'EMPTY_SECTION', location: heading || `section:${si}` });
    for (const [bi, block] of (section.blocks || []).entries()) { const loc = `${heading || si}/block:${bi}`; if (!BLOCK_TYPES.includes(block.type)) { issues.push({ type: 'INVALID_BLOCK_TYPE', location: loc }); continue; } const refs = Array.isArray(block.evidenceRefs) ? block.evidenceRefs : []; for (const id of refs) { const item = evidence.get(id); if (!item) issues.push({ type: 'UNKNOWN_EVIDENCE', location: loc, evidenceId: id }); else if (item.projectId !== evidencePack.projectId) issues.push({ type: 'CROSS_PROJECT_EVIDENCE', location: loc, evidenceId: id }); }
      const value = block.type === 'table' ? (block.rows || []).flat().join(' ') : block.text || (block.items || []).join(' '); if (/\b(TODO|TBD|INSERT HERE|Lorem ipsum)\b|\[(NAME|DATE)\]/i.test(value) && !specification.constraints.allowPlaceholders) issues.push({ type: 'UNRESOLVED_PLACEHOLDER', location: loc }); if (block.type === 'table' && (!Array.isArray(block.columns) || !block.columns.length || !Array.isArray(block.rows) || block.rows.some(row => !Array.isArray(row) || row.length !== block.columns.length))) issues.push({ type: 'MALFORMED_TABLE', location: loc });
      const cited = refs.map(id => evidence.get(id)?.text || '').join(' '), nums = String(value).match(/\b\d+(?:[.,]\d+)?%?\b/g) || [], dates = String(value).match(/\b(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},\s+\d{4}\b/gi) || []; for (const number of nums) { if (refs.length && !cited.includes(number)) issues.push({ type: 'UNSUPPORTED_NUMERIC_CLAIM', location: loc, value: number }); numberGroups[heading.toLowerCase().includes('summary') ? 'summary' : 'body'].add(number); } for (const date of dates) if (refs.length && !cited.toLowerCase().includes(date.toLowerCase())) issues.push({ type: 'UNSUPPORTED_DATE_CLAIM', location: loc, value: date }); if (value && /\b(?:was|were|completed|conducted|reported|achieved|total)\b/i.test(value) && !refs.length) issues.push({ type: 'UNSUPPORTED_CLAIM', location: loc });
    }
  }
  for (const required of specification.sections) if (![...headings].includes(required.toLowerCase())) issues.push({ type: 'REQUIRED_SECTION_MISSING', location: required }); if (numberGroups.summary.size && numberGroups.body.size && [...numberGroups.summary].some(number => !numberGroups.body.has(number))) issues.push({ type: 'SUMMARY_INCONSISTENCY', location: 'Executive Summary' }); if (JSON.stringify(ir || {}).length > 250000) issues.push({ type: 'DOCUMENT_TOO_LARGE', location: 'document' }); return { status: issues.length ? 'FAIL' : 'PASS', issues, fingerprint: fingerprint(ir), counts: { sections: ir?.sections?.length || 0, blocks: (ir?.sections || []).reduce((n, section) => n + (section.blocks?.length || 0), 0), evidence: evidence.size } };
}

export function deterministicDraft(specification, evidencePack, revision = 1) { return { metadata: { ...specification, revision }, sections: specification.sections.map((heading, index) => { if (/sources/i.test(heading)) return { id: `section-${index + 1}`, heading, blocks: evidencePack.items.slice(0, 10).map(item => ({ type: 'paragraph', text: item.provenance.filename, evidenceRefs: [item.id] })) }; const chosen = evidencePack.items[index % Math.max(1, evidencePack.items.length)]; return { id: `section-${index + 1}`, heading, blocks: chosen ? [{ type: 'paragraph', text: chosen.text, evidenceRefs: [chosen.id] }] : [{ type: 'paragraph', text: 'Available project records do not provide supporting evidence for this section.', evidenceRefs: [] }] }; }) }; }
