import JSZip from 'jszip';
import { createHash } from 'node:crypto';
import { mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { safeFilename } from './documentCore.js';
const esc = value => String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const run = (value, bold = false) => `<w:r>${bold ? '<w:rPr><w:b/></w:rPr>' : ''}<w:t xml:space="preserve">${esc(value)}</w:t></w:r>`;
const para = (value, style = null, numId = null) => `<w:p><w:pPr>${style ? `<w:pStyle w:val="${style}"/>` : ''}${numId ? `<w:numPr><w:ilvl w:val="0"/><w:numId w:val="${numId}"/></w:numPr>` : ''}</w:pPr>${run(value)}</w:p>`;
const table = block => `<w:tbl><w:tblPr><w:tblBorders><w:top w:val="single" w:sz="4"/><w:left w:val="single" w:sz="4"/><w:bottom w:val="single" w:sz="4"/><w:right w:val="single" w:sz="4"/><w:insideH w:val="single" w:sz="4"/><w:insideV w:val="single" w:sz="4"/></w:tblBorders></w:tblPr>${[block.columns, ...block.rows].map((row, i) => `<w:tr>${row.map(cell => `<w:tc><w:tcPr><w:tcW w:w="2400" w:type="dxa"/></w:tcPr><w:p>${run(cell, i === 0)}</w:p></w:tc>`).join('')}</w:tr>`).join('')}</w:tbl>`;
export async function renderDocx({ ir, outputDir, filename }) { const zip = new JSZip(), body = [para(ir.metadata.title, 'Title')]; for (const section of ir.sections) { body.push(para(section.heading, 'Heading1')); for (const block of section.blocks) { if (['paragraph', 'callout', 'signature_block'].includes(block.type)) body.push(para(block.text)); else if (block.type === 'bullet_list') for (const item of block.items) body.push(para(item, null, 1)); else if (block.type === 'numbered_list') for (const item of block.items) body.push(para(item, null, 2)); else if (block.type === 'table') body.push(table(block)); else if (block.type === 'page_break') body.push('<w:p><w:r><w:br w:type="page"/></w:r></w:p>'); } } const documentXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body.join('')}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1080" w:right="1080" w:bottom="1080" w:left="1080"/></w:sectPr></w:body></w:document>`;
  zip.file('[Content_Types].xml', `<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>`); zip.folder('_rels').file('.rels', `<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`); const word = zip.folder('word'); word.file('document.xml', documentXml); word.file('styles.xml', `<?xml version="1.0"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:rFonts w:ascii="Aptos"/><w:sz w:val="22"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:b/><w:sz w:val="36"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:style></w:styles>`); word.folder('_rels').file('document.xml.rels', `<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>`); const safe = safeFilename(filename || ir.metadata.title), target = path.join(outputDir, safe); await mkdir(outputDir, { recursive: true }); const buffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' }); await writeFile(target, buffer); return { path: target, filename: safe, mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', size: (await stat(target)).size, hash: createHash('sha256').update(buffer).digest('hex'), documentXml };
}
export async function validateDocx(file, expected = []) { const buffer = await readFile(file), zip = await JSZip.loadAsync(buffer), xml = await zip.file('word/document.xml')?.async('string'); const issues = []; if (!xml) issues.push('DOCUMENT_XML_MISSING'); for (const value of expected) if (!xml?.includes(esc(value))) issues.push(`EXPECTED_TEXT_MISSING:${value}`); return { status: issues.length ? 'FAIL' : 'PASS', issues, zip: Boolean(zip), documentXml: Boolean(xml), size: buffer.length, hash: createHash('sha256').update(buffer).digest('hex') }; }
