import { randomUUID } from 'node:crypto';
import { access, realpath } from 'node:fs/promises';
import path from 'node:path';
import { AI_ROLES } from '../models/aiSettingsService.js';

const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const fail = (code, message, status = 400) => Object.assign(new Error(message), { code, status });
const cleanText = (value, name, max, required = false) => { if (typeof value !== 'string' || required && !value.trim() || value.length > max || /[\0\r\n]/.test(value)) throw fail('PROJECT_INVALID', `Invalid ${name}.`); return value.trim(); };
const safeIds = (value, name) => { if (!Array.isArray(value) || value.length > 100 || value.some(id => !uuid.test(id))) throw fail('PROJECT_INVALID', `Invalid ${name}.`); return [...new Set(value)]; };
const publicProject = project => ({ id: project.id, name: project.name, description: project.description, workspaceId: project.workspaceId, workspace: { available: project.workspaceStatus === 'ACTIVE', location: project.workspaceRoot }, repositoryIds: project.repositoryIds, sourceIds: project.sourceIds, knowledgeProjectId: project.knowledgeProjectId, modelPreferences: project.modelPreferences, createdAt: project.createdAt, updatedAt: project.updatedAt });

export class ProjectService {
  constructor({ store, workspaces, registry, root }) { this.store = store; this.workspaces = workspaces; this.registry = registry; this.root = root; }
  async init() { await this.store.load(); for (const project of this.store.state.projects) await this.registerWorkspace(project); return this; }
  async registerWorkspace(project) { try { const registered = await this.workspaces.register({ projectId: project.id, root: project.workspaceRoot, allowedPaths: project.allowedPaths, deniedPaths: project.deniedPaths, testCommands: project.testCommands }); project.workspaceId = registered.workspaceId; project.workspaceStatus = 'ACTIVE'; } catch { project.workspaceId = null; project.workspaceStatus = 'WORKSPACE_UNAVAILABLE'; } }
  async resourceExists(kind, id) { const dir = kind === 'repository' ? 'repository-sources' : 'sources'; await access(path.join(this.root, 'data', dir, `${id}.json`)).catch(() => { throw fail(kind === 'repository' ? 'REPOSITORY_NOT_FOUND' : 'SOURCE_NOT_FOUND', `${kind} was not found.`, 404); }); }
  validatePreferences(value = {}) { if (!value || typeof value !== 'object' || Array.isArray(value)) throw fail('PROJECT_INVALID', 'Invalid model preferences.'); const result = {}; for (const [role, model] of Object.entries(value)) { if (!AI_ROLES.includes(role) || typeof model !== 'string') throw fail('PROJECT_INVALID', 'Invalid model preference.'); const found = this.registry?.get(model); if (!found?.enabled || !found.capabilities.includes('chat')) throw fail('MODEL_NOT_AVAILABLE', 'Project model is unavailable.'); result[role] = model; } return result; }
  async validateWorkspace(input, projectId) { if (!input || typeof input.root !== 'string' || !path.isAbsolute(input.root)) throw fail('WORKSPACE_INVALID', 'Workspace requires an absolute root.'); const allowedPaths = input.allowedPaths ?? ['.'], deniedPaths = input.deniedPaths ?? [], testCommands = input.testCommands ?? []; const registered = await this.workspaces.register({ projectId, root: input.root, allowedPaths, deniedPaths, testCommands }); return { workspaceId: registered.workspaceId, workspaceRoot: await realpath(input.root), workspaceStatus: 'ACTIVE', allowedPaths: registered.allowedPaths, deniedPaths: registered.deniedPaths, testCommands }; }
  async create(input = {}) { const id = randomUUID(), name = cleanText(input.name, 'project name', 100, true), description = cleanText(input.description || '', 'description', 1000), workspace = await this.validateWorkspace(input.workspace, id); const repositoryIds = safeIds(input.repositoryIds || [], 'repository IDs'), sourceIds = safeIds(input.sourceIds || [], 'source IDs'); await Promise.all(repositoryIds.map(value => this.resourceExists('repository', value))); await Promise.all(sourceIds.map(value => this.resourceExists('source', value))); const now = new Date().toISOString(), project = { id, name, description, ...workspace, repositoryIds, sourceIds, knowledgeProjectId: id, modelPreferences: this.validatePreferences(input.modelPreferences), createdAt: now, updatedAt: now }; this.store.state.projects.push(project); this.activity(id, 'PROJECT_CREATED', { projectId: id }); await this.store.save(); return publicProject(project); }
  get(id) { const project = this.store.state.projects.find(item => item.id === id); if (!project) throw fail('PROJECT_NOT_FOUND', 'Project was not found.', 404); return project; }
  list(query = '') { const value = String(query).toLowerCase().slice(0, 100); return this.store.state.projects.filter(item => !value || item.name.toLowerCase().includes(value) || item.description.toLowerCase().includes(value)).map(item => { const project = publicProject(item); project.workspace = { available: project.workspace.available }; return project; }); }
  async update(id, input = {}) { const project = this.get(id); if (input.name !== undefined) project.name = cleanText(input.name, 'project name', 100, true); if (input.description !== undefined) project.description = cleanText(input.description, 'description', 1000); if (input.repositoryIds !== undefined) { const ids = safeIds(input.repositoryIds, 'repository IDs'); await Promise.all(ids.map(value => this.resourceExists('repository', value))); project.repositoryIds = ids; } if (input.sourceIds !== undefined) { const ids = safeIds(input.sourceIds, 'source IDs'); await Promise.all(ids.map(value => this.resourceExists('source', value))); project.sourceIds = ids; } if (input.modelPreferences !== undefined) project.modelPreferences = this.validatePreferences(input.modelPreferences); project.updatedAt = new Date().toISOString(); this.activity(id, 'PROJECT_UPDATED', {}); await this.store.save(); return publicProject(project); }
  async delete(id, confirmed) { if (confirmed !== true) throw fail('CONFIRMATION_REQUIRED', 'Project deletion requires confirmation.'); this.get(id); if (this.store.state.missions.some(item => item.projectId === id && ['RUNNING', 'WAITING_APPROVAL'].includes(item.status))) throw fail('PROJECT_BUSY', 'Project has an active mission.', 409); this.store.state.projects = this.store.state.projects.filter(item => item.id !== id); this.store.state.missions = this.store.state.missions.filter(item => item.projectId !== id); this.store.state.runs = this.store.state.runs.filter(item => item.projectId !== id); this.store.state.activity = this.store.state.activity.filter(item => item.projectId !== id); await this.store.save(); return { deleted: true, detachedOnly: true }; }
  activity(projectId, type, details = {}) { const item = { eventId: randomUUID(), projectId, type, timestamp: new Date().toISOString(), details }; this.store.state.activity.push(item); if (this.store.state.activity.length > 1000) this.store.state.activity.shift(); return item; }
  events(projectId) { this.get(projectId); return this.store.state.activity.filter(item => item.projectId === projectId).slice(-100).reverse(); }
  public(id) { return publicProject(this.get(id)); }
}
