import { patchFingerprint } from '../development/patchProposal.js';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const runFile = promisify(execFile);

const ok = data => ({ status: 'success', data });
export function registerWorkspaceTools(registry, workspaces, tests) {
  registry.register({ id: 'workspace.list', name: 'List workspace', description: 'Bounded workspace listing.', capabilities: ['workspace-read'], riskLevel: 'SAFE', allowedAgentTypes: ['Developer', 'CodeReviewer'], requiresApproval: false, validateInput: input => Boolean(input?.workspaceId), execute: async input => ok(await workspaces.list(input)) });
  registry.register({ id: 'workspace.read', name: 'Read workspace file', description: 'Bounded text read.', capabilities: ['workspace-read'], riskLevel: 'SAFE', allowedAgentTypes: ['Developer', 'CodeReviewer', 'Test'], requiresApproval: false, validateInput: input => Boolean(input?.workspaceId && input?.relativePath), execute: async input => ok(await workspaces.read(input)) });
  registry.register({ id: 'repository.search', name: 'Search repository', description: 'Bounded text search.', capabilities: ['workspace-search'], riskLevel: 'SAFE', allowedAgentTypes: ['Developer', 'CodeReviewer'], requiresApproval: false, validateInput: input => Boolean(input?.workspaceId && input?.query), execute: async input => ok(await workspaces.search(input)) });
  registry.register({ id: 'workspace.gitRead', name: 'Read Git metadata', description: 'Read-only Git status, diff, or recent log.', capabilities: ['git-read'], riskLevel: 'SAFE', allowedAgentTypes: ['Developer', 'CodeReviewer'], requiresApproval: false, validateInput: input => Boolean(input?.workspaceId && ['status', 'diff', 'log'].includes(input?.action)), execute: async input => { const workspace = workspaces.get(input.workspaceId), args = input.action === 'status' ? ['status', '--short'] : input.action === 'diff' ? ['diff', '--', ...(input.paths || []).slice(0, 20)] : ['log', '-n', String(Math.min(input.limit || 5, 20)), '--oneline']; const result = await runFile('git', args, { cwd: workspace.canonicalRoot, timeout: 10000, windowsHide: true, maxBuffer: 100000 }); return ok({ action: input.action, output: result.stdout.slice(0, 50000), truncated: result.stdout.length > 50000 }); } });
  registry.register({ id: 'workspace.applyPatch', name: 'Apply approved patch', description: 'Apply an exact approved patch with rollback snapshot.', capabilities: ['workspace-write'], riskLevel: 'HIGH_RISK', allowedAgentTypes: ['Developer'], requiresApproval: true, validateInput: input => Boolean(input?.workspaceId && input?.proposal && input?.fingerprint), execute: async input => ok(await workspaces.apply({ workspaceId: input.workspaceId, proposal: input.proposal, patchFingerprint: patchFingerprint(input.proposal), expectedFingerprint: input.fingerprint, allowCreateFiles: input.allowCreateFiles, allowDeleteFiles: input.allowDeleteFiles })) });
  registry.register({ id: 'workspace.rollbackPatch', name: 'Rollback patch', description: 'Restore one Darkcry snapshot.', capabilities: ['workspace-write'], riskLevel: 'HIGH_RISK', allowedAgentTypes: ['Developer'], requiresApproval: true, validateInput: input => Boolean(input?.snapshotId), execute: async input => ok(await workspaces.restore(input.snapshotId)) });
  registry.register({ id: 'workspace.runTest', name: 'Run registered test', description: 'Execute one structured allowlisted test command.', capabilities: ['test'], riskLevel: 'CONTROLLED', allowedAgentTypes: ['Test', 'Developer'], requiresApproval: false, validateInput: input => Boolean(input?.workspaceId && input?.commandId), execute: async input => { const result = await tests.run(workspaces.get(input.workspaceId), input.commandId); return ok(result); } });
}
